/// Generated by AssetsRefGenerator on 2021/10/17
class Res {
  static const String detalhe1 = "assets/detalhe1.png";
  static const String detalhe2 = "assets/detalhe2.png";
  static const String fundo = "assets/fundo.png";
}
